# Generated by Django 4.0.4 on 2022-04-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexistore', '0005_order_orderdetails_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flexistore.order'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flexistore.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flexistore.uom'),
        ),
    ]
